Fix -Wint-conversion warning
The previous line has a cast to (u8*) as well, so it should be fine to
put it here too. It doesn't change behavior.

source/zone.c:122:22: error: initialization of 'u8 *' {aka 'unsigned char *'} from 'long unsigned int' makes pointer from integer without a cast [-Wint-conversion]
  122 |         u8* dst64a = ((u32)dst8&~0x3F);
      |                      ^