Fix errors about missing M_PI_DIV_180
Some code was using this macro instead of DEG2RAD and RAD2DEG for
conversions.

source/psp/video_hardware_main.cpp: In function 'void R_DrawSpriteModel(entity_t*)':
source/psp/video_hardware_main.cpp:782:55: error: 'M_PI_DIV_180' was not declared in this scope
  782 |                 angle = currententity->angles[ROLL] * M_PI_DIV_180;
      |                                                       ^~~~~~~~~~~~